// This file is auto-generated by: npm run db:types
// Do not edit manually — run `npm run db:types` to regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          email: string;
          avatar_url: string | null;
          default_currency: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          email: string;
          avatar_url?: string | null;
          default_currency?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          email?: string;
          avatar_url?: string | null;
          default_currency?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      expense_categories: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          icon: string | null;
          color: string | null;
          is_default: boolean;
          is_active: boolean;
          sort_order: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          icon?: string | null;
          color?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          sort_order?: number;
          created_at?: string;
        };
        Update: {
          name?: string;
          icon?: string | null;
          color?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          sort_order?: number;
        };
        Relationships: [];
      };
      payment_methods: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          type: Database["public"]["Enums"]["payment_method_type"];
          last_four: string | null;
          is_default: boolean;
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          type?: Database["public"]["Enums"]["payment_method_type"];
          last_four?: string | null;
          is_default?: boolean;
          is_active?: boolean;
          created_at?: string;
        };
        Update: {
          name?: string;
          type?: Database["public"]["Enums"]["payment_method_type"];
          last_four?: string | null;
          is_default?: boolean;
          is_active?: boolean;
        };
        Relationships: [];
      };
      trips: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          destination: string | null;
          client: string | null;
          start_date: string | null;
          end_date: string | null;
          status: Database["public"]["Enums"]["trip_status"];
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          destination?: string | null;
          client?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: Database["public"]["Enums"]["trip_status"];
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          name?: string;
          destination?: string | null;
          client?: string | null;
          start_date?: string | null;
          end_date?: string | null;
          status?: Database["public"]["Enums"]["trip_status"];
          notes?: string | null;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      projects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          client: string | null;
          status: Database["public"]["Enums"]["project_status"];
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          client?: string | null;
          status?: Database["public"]["Enums"]["project_status"];
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          name?: string;
          description?: string | null;
          client?: string | null;
          status?: Database["public"]["Enums"]["project_status"];
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      reimbursement_batches: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          description: string | null;
          status: Database["public"]["Enums"]["batch_status"];
          submitted_at: string | null;
          approved_at: string | null;
          paid_at: string | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["batch_status"];
          submitted_at?: string | null;
          approved_at?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["batch_status"];
          submitted_at?: string | null;
          approved_at?: string | null;
          paid_at?: string | null;
          notes?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          description: string | null;
          amount: number;
          currency: string;
          expense_date: string;
          vendor_name: string | null;
          vendor_country: string | null;
          category_id: string | null;
          payment_method_id: string | null;
          trip_id: string | null;
          project_id: string | null;
          batch_id: string | null;
          receipt_status: Database["public"]["Enums"]["receipt_status"];
          reimbursement_status: Database["public"]["Enums"]["reimbursement_status"];
          is_personal: boolean;
          notes: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          description?: string | null;
          amount: number;
          currency: string;
          expense_date: string;
          vendor_name?: string | null;
          vendor_country?: string | null;
          category_id?: string | null;
          payment_method_id?: string | null;
          trip_id?: string | null;
          project_id?: string | null;
          batch_id?: string | null;
          receipt_status?: Database["public"]["Enums"]["receipt_status"];
          reimbursement_status?: Database["public"]["Enums"]["reimbursement_status"];
          is_personal?: boolean;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          title?: string;
          description?: string | null;
          amount?: number;
          currency?: string;
          expense_date?: string;
          vendor_name?: string | null;
          vendor_country?: string | null;
          category_id?: string | null;
          payment_method_id?: string | null;
          trip_id?: string | null;
          project_id?: string | null;
          batch_id?: string | null;
          receipt_status?: Database["public"]["Enums"]["receipt_status"];
          reimbursement_status?: Database["public"]["Enums"]["reimbursement_status"];
          is_personal?: boolean;
          notes?: string | null;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      receipts: {
        Row: {
          id: string;
          expense_id: string;
          user_id: string;
          file_path: string;
          file_name: string;
          file_type: string;
          file_size: number;
          ocr_raw: Json | null;
          uploaded_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          expense_id: string;
          user_id: string;
          file_path: string;
          file_name: string;
          file_type: string;
          file_size: number;
          ocr_raw?: Json | null;
          uploaded_at?: string;
          created_at?: string;
        };
        Update: {
          ocr_raw?: Json | null;
        };
        Relationships: [];
      };
      import_sessions: {
        Row: {
          id: string;
          user_id: string;
          file_name: string;
          file_type: string;
          status: Database["public"]["Enums"]["import_status"];
          raw_data: Json | null;
          transaction_count: number | null;
          imported_count: number;
          skipped_count: number;
          error_message: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          file_name: string;
          file_type: string;
          status?: Database["public"]["Enums"]["import_status"];
          raw_data?: Json | null;
          transaction_count?: number | null;
          imported_count?: number;
          skipped_count?: number;
          error_message?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          status?: Database["public"]["Enums"]["import_status"];
          raw_data?: Json | null;
          transaction_count?: number | null;
          imported_count?: number;
          skipped_count?: number;
          error_message?: string | null;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      import_transactions: {
        Row: {
          id: string;
          session_id: string;
          user_id: string;
          raw_date: string | null;
          raw_amount: string | null;
          raw_currency: string | null;
          raw_merchant: string | null;
          raw_description: string | null;
          mapped_expense_id: string | null;
          status: Database["public"]["Enums"]["import_transaction_status"];
          duplicate_of_id: string | null;
          duplicate_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          session_id: string;
          user_id: string;
          raw_date?: string | null;
          raw_amount?: string | null;
          raw_currency?: string | null;
          raw_merchant?: string | null;
          raw_description?: string | null;
          mapped_expense_id?: string | null;
          status?: Database["public"]["Enums"]["import_transaction_status"];
          duplicate_of_id?: string | null;
          duplicate_score?: number | null;
          created_at?: string;
        };
        Update: {
          mapped_expense_id?: string | null;
          status?: Database["public"]["Enums"]["import_transaction_status"];
          duplicate_of_id?: string | null;
          duplicate_score?: number | null;
        };
        Relationships: [];
      };
    };
    Views: {
      expense_summary: {
        Row: {
          user_id: string;
          draft_count: number;
          ready_count: number;
          submitted_count: number;
          approved_count: number;
          paid_count: number;
          rejected_count: number;
          missing_receipts_count: number;
          pending_amount: number | null;
          submitted_amount: number | null;
          approved_amount: number | null;
        };
        Relationships: [];
      };
    };
    Functions: Record<string, never>;
    Enums: {
      reimbursement_status:
        | "draft"
        | "ready"
        | "submitted"
        | "approved"
        | "paid"
        | "rejected";
      receipt_status: "not_required" | "required_missing" | "uploaded";
      trip_status: "planning" | "active" | "completed" | "cancelled";
      project_status: "active" | "completed" | "archived";
      batch_status: "draft" | "submitted" | "approved" | "paid" | "rejected";
      payment_method_type:
        | "credit_card"
        | "debit_card"
        | "cash"
        | "bank_transfer"
        | "paypal"
        | "apple_pay"
        | "google_pay"
        | "other";
      import_status:
        | "pending"
        | "processing"
        | "review"
        | "completed"
        | "failed";
      import_transaction_status:
        | "pending"
        | "imported"
        | "skipped"
        | "duplicate";
    };
    CompositeTypes: Record<string, never>;
  };
};
